// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeNUSk1PUHkF-CWDxG_cxn7hHzhc3Tf5U',
    appId: '1:709454915450:web:5c7c5ae1de5eb7dcce58c3',
    messagingSenderId: '709454915450',
    projectId: 'pegki-e0872',
    authDomain: 'pegki-e0872.firebaseapp.com',
    storageBucket: 'pegki-e0872.firebasestorage.app',
    measurementId: 'G-ZLP1GES1GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGDrB1w4fC7X7HRWd7QsMbW4kLmjyWyyQ',
    appId: '1:709454915450:android:58420ba410ef26e1ce58c3',
    messagingSenderId: '709454915450',
    projectId: 'pegki-e0872',
    storageBucket: 'pegki-e0872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV3VxDjJlBMl0CNoPcyixK3t1kcMQmGpI',
    appId: '1:709454915450:ios:ea9ec9a1062b9a2dce58c3',
    messagingSenderId: '709454915450',
    projectId: 'pegki-e0872',
    storageBucket: 'pegki-e0872.firebasestorage.app',
    iosBundleId: 'com.example.pekiBabyCare',
  );
}
